// exocore-web/templates/vite-svelte/src/App.svelte
<script lang="ts">
  let count = 0
</script>

<main>
  <h1>⚡ Exocore Svelte</h1>
  <p>Edit <code>src/App.svelte</code> to get started</p>
  <button on:click={() => count++}>count is {count}</button>
</main>

<style>
  :global(*) { margin: 0; padding: 0; box-sizing: border-box; }
  :global(body) { background: #0f0f0f; color: #fff; font-family: sans-serif; }
  main { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; gap: 1rem; }
  h1 { font-size: 2.5rem; }
  p { opacity: 0.6; }
  button { padding: 0.75rem 2rem; font-size: 1rem; border-radius: 8px; border: none; background: #ff3e00; color: #fff; cursor: pointer; font-weight: 700; }
</style>

// exocore-web/templates/vite-solid/src/App.tsx
import { createSignal } from 'solid-js'

export default function App() {
  const [count, setCount] = createSignal(0)

  return (
    <div style={{ display: 'flex', 'flex-direction': 'column', 'align-items': 'center', 'justify-content': 'center', 'min-height': '100vh', 'font-family': 'sans-serif', background: '#0f0f0f', color: '#fff', gap: '1rem' }}>
      <h1 style={{ 'font-size': '2.5rem' }}>⚡ Exocore Solid</h1>
      <p style={{ opacity: '0.6' }}>Edit <code>src/App.tsx</code> to get started</p>
      <button
        onClick={() => setCount(c => c + 1)}
        style={{ padding: '0.75rem 2rem', 'font-size': '1rem', 'border-radius': '8px', border: 'none', background: '#2c4f7c', color: '#fff', cursor: 'pointer', 'font-weight': '700' }}
      >
        count is {count()}
      </button>
    </div>
  )
}
